export const LOAD_USER_DETAILS_FROM_CACH = 'LOAD_USER_DETAILS_FROM_CACH';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

export const LOAD_SETTINGS_FROM_CACH = 'LOAD_SETTINGS_FROM_CACH';
export const SET_SETTINGS = 'SET_SETTINGS';